### ISSUE TITLE
remote host has disconnected

### ISSUE THREAD

**Issue by daslicht** [dstuecken/sshfs-gui#11]
Hi,
I get anytime "remote host has disconnected" any idea what could be wrong ?

I am using macOS Sierra

**Comment by dstuecken** [comment]
I think your ssh server is not sftp enabled. Check the sshd config.

**Comment by sheldonwjones** [comment]
I'm getting the same results. Everything works if I copy the sshfs command line and paste it into a terminal. The password prompt comes up and the server is mounted after I type the password in. I don't think the gui is sending the password.

Any thought?

**Comment by daslicht** [comment]
manual using sshfs in cli works , so it is not the server.

Today I tried it again and now I get : 
```SSHFS console utility missing```

Where to get that Utility ? It seams be be no longer available here:

https://pqrs.org/osx/

**Comment by dstuecken** [comment]
It should usually work if you install sshfs and fuse from here: https://osxfuse.github.io/
Restart your system after installing.

**Comment by daslicht** [comment]
I have  meanwhile just created a shell script (command)

**Comment by MagnusOxlund** [comment]
Just to provide a datapoint for anyone else arriving here, I get the same `remote host has disconnected` error when using the macFuse `sshfs` binary rather than the default binary bundled with the GUI.

**Comment by daslicht** [comment]
I meanwhiule use [MountainDuck](https://mountainduck.io)
