### ISSUE TITLE
What are all these command line options? Can I remove them in some way?

### ISSUE THREAD

**Issue by i0ntempest** [dstuecken/sshfs-gui#13]
GUI tries to use this command: 
`/opt/local/bin/sshfs 'Admin@xxx.xxx.xxx.xxx:/' '/Volumes/iMacSFTP' -p 22  -o workaround=nonodelay -ovolname='Admin@99.227.128.125' -oNumberOfPasswordPrompts=1 -o transform_symlinks -o idmap=user  >/tmp/sshfs-tmp.err 2>&1`
and returns error: unknown workaround: nonodelay
But actually to connect and mount I only need this command:
`sudo sshfs -o allow_other,defer_permissions Admin@xxx.xxx.xxx.xxx:/ /Volumes/iMacSFTP`
Is there a way I can remove those options causing troubles?

**Comment by dstuecken** [comment]
Not from the packaged version. Did you compile the tool?

**Comment by tempesti0n1c** [comment]
No, I had to use the pkg installer bcuz MacPorts rejects to compile it [https://trac.macports.org/ticket/55021]. sshfs and osxfuse are installed via MacPorts. Btw I noticed that these weird command line args are also in your screenshots.
