### ISSUE TITLE
Import OSXFuse into the app

### ISSUE THREAD

**Issue by HTKT** [dstuecken/sshfs-gui#5]
Thanks for this library.

But it will be better if you can import OSXFuse framework into your app so i just intall the app and run, no need to install other things? Is it possible? Thanks

**Comment by dstuecken** [comment]
Thanks for your request. I'll have a look and see what i can do :-)

**Comment by dstuecken** [comment]
There is a new option Bundled MacFUSE now. Could you check if it is working?

**Comment by Refbonusjunkiescoclouvier** [comment]
[sftp-server(8) - OpenBSD manual pages.pdf](https://github.com/user-attachments/files/17311768/sftp-server.8.-.OpenBSD.manual.pages.pdf)
