### ISSUE TITLE
Crash at mount time

### ISSUE THREAD

**Issue by manu0401** [dstuecken/sshfs-gui#8]
On MacOS X 10.11.3, SSHFS GUI crashes at mount time. If launched from Finder, the mount dies with the app. If started from the Terminal, the mount remain after the app crashes.

The details produced by OSX  are attached. It seems there is a strlen() used on a NULL pointer:
[crash.txt](https://github.com/dstuecken/sshfs-gui/files/255290/crash.txt)

**Comment by dstuecken** [comment]
Should be fixed!
